#!/bin/bash

msg=$2
msg="${msg// /_}"

PATH_NOTIFY=$(realpath /usr/local/bin/notify)
PATH_NOTIFY=$(dirname $PATH_NOTIFY)

DISCORD=$PATH_NOTIFY/notifier
DOTENV=$PATH_NOTIFY/.env

python3 $DISCORD $DOTENV $1 $msg
